# Generated by Django 5.0.7 on 2024-08-09 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('bus_id', models.AutoField(primary_key=True, serialize=False)),
                ('bus_number', models.CharField(max_length=255)),
                ('conductor_name', models.CharField(max_length=255)),
                ('conductor_number', models.CharField(max_length=15)),
                ('seat1', models.BooleanField(default=False)),
                ('seat2', models.BooleanField(default=False)),
                ('seat3', models.BooleanField(default=False)),
                ('seat4', models.BooleanField(default=False)),
                ('seat5', models.BooleanField(default=False)),
                ('seat6', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('stop_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(primary_key=True, serialize=False)),
                ('starting', models.CharField(max_length=255)),
                ('ending', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fare_destination', to='Booking.busstop')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fare_source', to='Booking.busstop')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.route')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_user', to=settings.AUTH_USER_MODEL)),
                ('bus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_bus', to='Booking.bus')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_destination', to='Booking.busstop')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_source', to='Booking.busstop')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_price', to='Booking.fare')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('aadhar', models.IntegerField(null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='busstop',
            name='route_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='Booking.route'),
        ),
        migrations.AddField(
            model_name='bus',
            name='route_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='Booking.route'),
        ),
        migrations.CreateModel(
            name='BusSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.bus')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.busstop')),
            ],
            options={
                'unique_together': {('bus', 'stop', 'arrival_time')},
            },
        ),
    ]
