# Generated by Django 5.0.7 on 2024-08-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seat_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
