# Generated by Django 5.0.7 on 2024-08-19 12:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_booking_seat_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='bus_id',
            new_name='bus',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seat_no',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='seat1',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='seat2',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='seat3',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='seat4',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='seat5',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='seat6',
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=5)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Booking.bus')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='seat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Booking.seat'),
            preserve_default=False,
        ),
    ]
